build.gradle
src/main/java/site/goldenticket/common/redis/config/EmbeddedRedisConfig.java
src/main/java/site/goldenticket/common/redis/config/RedisConfig.java
src/main/java/site/goldenticket/common/redis/service/RedisService.java
src/main/java/site/goldenticket/common/redis/service/RedisServiceImpl.java
src/test/java/site/goldenticket/common/RedisServiceTest.java

Redis 설정
- RedisConfig.class
- Redis Template 사용을 위한 설정
- EmbeddedRedisConfig.class
- Test Container를 사용하여 Docker를 통한 Embedded Redis 설정
- Default, Local 환경에서 활성화
- RedisService
-Redis Template 범용적 사용을 위한 로직 구현
```
추가로... Default, Local 환경에서 Embedded 환경의 Redis를 사용하려고 하다보니..
Test Container 라이브러리 의존성의 scope이 test 가 아닌, compile로 설정하였습니다..
이 부분에 대해 다른분들의 의견을 듣고싶습니다!
```

Feature/1 Redis 설정

---

build.gradle
src/main/java/site/goldenticket/common/constants/AreaCode.java
src/main/java/site/goldenticket/common/constants/ReservationStatus.java
src/main/java/site/goldenticket/common/constants/ReservationType.java
src/main/java/site/goldenticket/reservation/controller/ReservationController.java
src/main/java/site/goldenticket/reservation/model/Reservation.java
src/main/java/site/goldenticket/reservation/repository/ReservationRepository.java
src/main/java/site/goldenticket/reservation/service/ReservationService.java

Feature/15 Reservation Package 설정

---

src/main/java/site/goldenticket/common/response/ErrorCode.java
src/main/java/site/goldenticket/common/security/SecurityConfiguration.java
src/main/java/site/goldenticket/common/security/authentication/SecurityAuthenticationFailureHandler.java
src/main/java/site/goldenticket/common/security/authentication/SecurityAuthenticationSuccessHandler.java
src/main/java/site/goldenticket/common/security/authentication/TokenProvider.java
src/main/java/site/goldenticket/common/security/authorization/SecurityAccessDeniedHandler.java
src/main/java/site/goldenticket/common/security/authorization/SecurityAuthenticationEntryPoint.java
src/main/java/site/goldenticket/common/security/authorization/SecurityErrorCode.java
src/main/java/site/goldenticket/common/security/authorization/TokenAuthorityConfigurer.java
src/main/java/site/goldenticket/common/security/authorization/TokenAuthorizationFilter.java
src/main/java/site/goldenticket/common/security/exception/InvalidJwtException.java
src/main/resources/application.yml

Spring Security 인가 구현
- Token을 통한 검증 Filter 구현
- 인증/인가 실패 Handler 구현

Spring Security 인가 구현

---

src/main/java/site/goldenticket/common/constants/PriceRange.java
src/main/java/site/goldenticket/common/pagination/constants/PaginationConstants.java
src/main/java/site/goldenticket/common/pagination/slice/CustomSlice.java
src/main/java/site/goldenticket/common/redis/constants/RedisConstants.java
src/main/java/site/goldenticket/common/redis/service/RedisService.java
src/main/java/site/goldenticket/common/redis/service/RedisServiceImpl.java
src/main/java/site/goldenticket/common/response/ErrorCode.java
src/main/java/site/goldenticket/common/util/IdGeneratorUtil.java
src/main/java/site/goldenticket/domain/product/controller/ProductController.java
src/main/java/site/goldenticket/domain/product/dto/ProductRequest.java
src/main/java/site/goldenticket/domain/product/dto/ProductResponse.java
src/main/java/site/goldenticket/domain/product/dto/SearchProductResponse.java
src/main/java/site/goldenticket/domain/product/model/Product.java
src/main/java/site/goldenticket/domain/product/repository/ProductRepository.java
src/main/java/site/goldenticket/domain/product/repository/ProductRepositoryCustom.java
src/main/java/site/goldenticket/domain/product/repository/ProductRepositoryImpl.java
src/main/java/site/goldenticket/domain/product/service/ProductService.java
src/main/java/site/goldenticket/domain/search/controller/SearchController.java
src/main/java/site/goldenticket/domain/search/dto/SearchHistoryRequest.java
src/main/java/site/goldenticket/domain/search/dto/SearchHistoryResponse.java
src/main/java/site/goldenticket/domain/search/dto/SearchResponse.java
src/main/java/site/goldenticket/domain/search/model/SearchHistory.java
src/main/java/site/goldenticket/domain/search/service/SearchService.java

1. 검색 이력 저장, 조회, 삭제 기능 구현
2. 실시간 검색 순위 집계를 위한 기능 구현
3. 검색 결과 페이지네이션 기능 구현

Feature/10 검색 기능 구현

---

src/main/java/site/goldenticket/common/response/ErrorCode.java
src/main/java/site/goldenticket/domain/user/controller/UserController.java
src/main/java/site/goldenticket/domain/user/dto/AgreementRequest.java
src/main/java/site/goldenticket/domain/user/dto/JoinRequest.java
src/main/java/site/goldenticket/domain/user/dto/JoinResponse.java
src/main/java/site/goldenticket/domain/user/entity/Agreement.java
src/main/java/site/goldenticket/domain/user/entity/User.java
src/main/java/site/goldenticket/domain/user/repository/UserRepository.java
src/main/java/site/goldenticket/domain/user/service/UserService.java
src/test/java/site/goldenticket/common/utils/UserUtils.java
src/test/java/site/goldenticket/domain/user/controller/UserControllerTest.java

- 이메일 저장소 존재 여부 확인
- 닉네임 저장소 존재 여부 확인

중복 확인 로직 구현

---

src/main/java/site/goldenticket/common/response/ErrorCode.java
src/main/java/site/goldenticket/common/security/SecurityConfiguration.java
src/main/java/site/goldenticket/domain/user/controller/UserController.java
src/main/java/site/goldenticket/domain/user/dto/AgreementRequest.java
src/main/java/site/goldenticket/domain/user/dto/JoinRequest.java
src/main/java/site/goldenticket/domain/user/dto/JoinResponse.java
src/main/java/site/goldenticket/domain/user/entity/Agreement.java
src/main/java/site/goldenticket/domain/user/entity/User.java
src/main/java/site/goldenticket/domain/user/repository/UserRepository.java
src/main/java/site/goldenticket/domain/user/service/UserService.java
src/test/java/site/goldenticket/common/utils/UserUtils.java
src/test/java/site/goldenticket/domain/user/controller/UserControllerTest.java

close #39 
- 이메일/닉네임 중복확인
- 회원가입

Feature/39 회원가입

---

src/main/java/site/goldenticket/common/response/CommonResponse.java
src/main/java/site/goldenticket/common/response/ErrorCode.java
src/main/java/site/goldenticket/common/security/SecurityConfiguration.java
src/main/java/site/goldenticket/common/security/authentication/SecurityAuthenticationSuccessHandler.java
src/main/java/site/goldenticket/common/security/authentication/dto/AuthenticationToken.java
src/main/java/site/goldenticket/common/security/authentication/token/TokenProvider.java
src/main/java/site/goldenticket/common/security/authentication/token/TokenService.java
src/main/java/site/goldenticket/common/security/authentication/token/TokenServiceImpl.java
src/main/java/site/goldenticket/common/security/authentication/token/dto/Token.java
src/main/java/site/goldenticket/common/security/authorization/TokenAuthorityConfigurer.java
src/main/java/site/goldenticket/common/security/authorization/TokenAuthorizationFilter.java
src/main/java/site/goldenticket/domain/security/controller/SecurityController.java
src/main/java/site/goldenticket/domain/security/dto/YanoljaUserResponse.java
src/main/java/site/goldenticket/domain/security/service/SecurityService.java
src/main/java/site/goldenticket/domain/user/repository/UserRepository.java
src/main/java/site/goldenticket/dummy/yauser/model/YaUser.java
src/main/java/site/goldenticket/dummy/yauser/service/YaUserService.java
src/main/resources/script/schema.sql
src/test/java/site/goldenticket/common/TokenProviderTest.java

소셜 로그인 로직
1. 야놀자 더미데이터에서 email, password 검증
2. 매칭되는 email, password가 있다면 야놀자 정보 반환
3. 로그인 결과 반환
- 반환값은 야놀자 ID에 따라 각각 다른 값을 반환합니다.
1. 야놀자 ID가 등록된 계정이 있다면 -> 토큰 반환
2. 야놀자 ID가 등록된 계정이 없다면 -> 야놀자 정보 반환
두 가지의 타입을 반환하다 보니... 반환 타입을 와일트 카드(`?`)를 사용했습니다.
위 로직은 `SecurityController`와 `SecurityService` 파일만 봐주시면 될 것 같습니다!

야놀자 로그인 구현

---

src/main/java/site/goldenticket/common/response/CommonResponse.java
src/main/java/site/goldenticket/common/response/ErrorCode.java
src/main/java/site/goldenticket/common/security/SecurityConfiguration.java
src/main/java/site/goldenticket/common/security/authentication/SecurityAuthenticationSuccessHandler.java
src/main/java/site/goldenticket/common/security/authentication/dto/AuthenticationToken.java
src/main/java/site/goldenticket/common/security/authentication/token/TokenProvider.java
src/main/java/site/goldenticket/common/security/authentication/token/TokenService.java
src/main/java/site/goldenticket/common/security/authentication/token/TokenServiceImpl.java
src/main/java/site/goldenticket/common/security/authentication/token/dto/Token.java
src/main/java/site/goldenticket/common/security/authorization/TokenAuthorityConfigurer.java
src/main/java/site/goldenticket/common/security/authorization/TokenAuthorizationFilter.java
src/main/java/site/goldenticket/domain/security/controller/SecurityController.java
src/main/java/site/goldenticket/domain/security/dto/YanoljaUserResponse.java
src/main/java/site/goldenticket/domain/security/service/SecurityService.java
src/main/java/site/goldenticket/domain/user/repository/UserRepository.java
src/main/java/site/goldenticket/dummy/yauser/controller/YaUserController.java
src/main/java/site/goldenticket/dummy/yauser/dto/YaUserRequest.java
src/main/java/site/goldenticket/dummy/yauser/dto/YaUserResponse.java
src/main/java/site/goldenticket/dummy/yauser/model/YaUser.java
src/main/java/site/goldenticket/dummy/yauser/repository/YaUserRepository.java
src/main/java/site/goldenticket/dummy/yauser/service/YaUserService.java
src/main/resources/script/schema.sql
src/test/java/site/goldenticket/common/TokenProviderTest.java

Feature/41 야놀자 로그인 구현

---

src/main/java/site/goldenticket/domain/user/dto/JoinRequest.java
src/test/java/site/goldenticket/common/utils/UserUtils.java

Hotfix: 회원가입 휴대폰 번호 포맷 변경

---

src/main/java/site/goldenticket/domain/chat/controller/ChatController.java
src/main/java/site/goldenticket/domain/chat/entity/Chat.java
src/main/java/site/goldenticket/domain/chat/entity/ChatRoom.java
src/main/java/site/goldenticket/domain/chat/entity/SenderType.java
src/main/java/site/goldenticket/domain/chat/repository/ChatRepository.java
src/main/java/site/goldenticket/domain/chat/repository/ChatRoomRepository.java
src/main/java/site/goldenticket/domain/chat/service/ChatService.java

개발내용
-
- Entity: Chat(채팅), ChatRoom(채팅방)
- Enum: SenderType (송신자 타입) 
- Controller, Service, Repository

feat: 채팅 패키지 설계

---

src/main/java/site/goldenticket/common/response/ErrorCode.java
src/main/java/site/goldenticket/common/security/authorization/TokenAuthorizationFilter.java
src/main/java/site/goldenticket/common/security/exception/InvalidJwtException.java
src/main/java/site/goldenticket/domain/user/entity/User.java

closed #71 
- AccessToken 앞에 Granted Type 제거 후 Redis 조회

fix: Token 검증 필터에서 Redis 조회할 때, Prefix 제거

---

src/main/java/site/goldenticket/domain/chat/controller/ChatController.java
src/main/java/site/goldenticket/domain/chat/dto/ChatRequest.java
src/main/java/site/goldenticket/domain/chat/service/ChatService.java

개발 내용
-
- 채팅 저장 기능 구현
전달 사항
-
- 프론트에서 채팅보내줄지 백에서 알아서 저장할지 미결정. 
- 우선 API 만들어둠

feat: 채팅 등록 API 구현

---

src/main/java/site/goldenticket/domain/chat/dto/ChatResponse.java
src/main/java/site/goldenticket/domain/chat/dto/ChatRoomShortResponse.java
src/main/java/site/goldenticket/domain/chat/entity/Chat.java
src/main/java/site/goldenticket/domain/chat/service/ChatService.java

- 채팅 Entity에 viewed 추가
- 채팅 저장 시, viewed=false로 저장
- 채팅방 조회 시, viewed = true로 수정
- 채팅방 목록 조회 시, 마지막 채팅 읽음 여부(viewed) 전달

feat: 채팅 조회여부 관리 기능 구현

---

src/main/resources/script/schema.sql

- 채팅 조회 여부 viewed 필드 추가
- 따옴표 삭제

Feature/76 채팅 DB 수정

---

src/main/java/site/goldenticket/common/security/SecurityConfiguration.java
src/main/java/site/goldenticket/domain/alert/controller/AlertController.java
src/main/java/site/goldenticket/domain/alert/dto/AlertRequest.java
src/main/java/site/goldenticket/domain/alert/service/AlertService.java

개발 내용
-
- 프론트 테스트용 알림 등록 기능 구현

feat: 테스트용 알림 등록 API 구현

---

src/main/java/site/goldenticket/common/response/ErrorCode.java
src/main/java/site/goldenticket/domain/payment/service/PaymentService.java
src/main/java/site/goldenticket/domain/user/service/UserService.java
src/main/java/site/goldenticket/domain/user/wish/controller/WishController.java
src/main/java/site/goldenticket/domain/user/wish/entity/WishProduct.java
src/main/java/site/goldenticket/domain/user/wish/repository/WishProductRepository.java
src/main/java/site/goldenticket/domain/user/wish/repository/WishRepository.java
src/main/java/site/goldenticket/domain/user/wish/service/WishService.java
src/main/resources/script/schema.sql
src/test/java/site/goldenticket/common/SecurityTest.java
src/test/java/site/goldenticket/common/config/ApiTest.java
src/test/java/site/goldenticket/common/utils/UserUtils.java
src/test/java/site/goldenticket/domain/user/controller/UserControllerTest.java
src/test/java/site/goldenticket/domain/user/wish/controller/WishProductControllerTest.java

closed #108 
- 관심 상품 삭제 API 구현 및 테스트

Feature/108 관심 상품 삭제

---

src/main/java/site/goldenticket/domain/chat/entity/Chat.java
src/main/java/site/goldenticket/domain/chat/service/ChatService.java
src/main/resources/script/schema.sql

개발 내용
-
- 스키마 SQL 수정
- 유저 타입별 조회여부 추가 및 관련 로직 수정
- 채팅 Service단 메서드레벨 주석 추가

Feature/58 chat viewed type 채팅 조회여부 타입 추가 및 주석 추가

---

src/main/java/site/goldenticket/domain/chat/service/ChatService.java
src/main/java/site/goldenticket/domain/payment/repository/OrderRepository.java

개발 내용
-
- 네고가 고려한 가격 설정 메서드 구현
- 아직 반영하진않음
- 테스트 후 반영예정

Feature/58 chat nego price 네고가 고려한 채팅방 가격 결정 메서드 구현

---

src/main/java/site/goldenticket/domain/chat/entity/Chat.java
src/main/resources/script/schema.sql

당장의 테스트를 위해 변경했던 사항 원상 복귀 : viewed 필드 삭제
- ddl 변경 (viewed 삭제)
- Chat 에서 viewed 삭제
- buyerId는 유지하기로! 
- Chat, ChatRoom PK 설정 추가

Feature/chat db reset 채팅 DB 재수정

---

src/main/java/site/goldenticket/domain/chat/dto/response/ChatRoomInfoResponse.java
src/main/java/site/goldenticket/domain/chat/service/ChatService.java

- 채팅방 상세 조회에 수신자 ID 추가
- 채팅방 상세 조회에 거래 진행상태 추가

feat: 채팅방 상세 조회 응답 DTO 데이터 수정

---

src/main/java/site/goldenticket/domain/user/controller/UserController.java
src/main/java/site/goldenticket/domain/user/entity/User.java
src/main/java/site/goldenticket/domain/user/service/UserService.java
src/test/java/site/goldenticket/domain/user/controller/UserControllerTest.java

closed #134 
- 계좌 삭제 구현 및 통합 테스트

Feature/134 계좌 삭제 구현

---

src/main/java/site/goldenticket/common/response/ErrorCode.java
src/main/java/site/goldenticket/domain/security/dto/YanoljaLoginResponse.java
src/main/java/site/goldenticket/domain/security/service/SecurityService.java
src/main/java/site/goldenticket/domain/user/controller/UserController.java
src/main/java/site/goldenticket/domain/user/dto/AccountResponse.java
src/main/java/site/goldenticket/domain/user/dto/RegisterAccountRequest.java
src/main/java/site/goldenticket/domain/user/entity/User.java
src/main/java/site/goldenticket/domain/user/service/UserService.java
src/test/java/site/goldenticket/common/config/ApiTest.java
src/test/java/site/goldenticket/common/utils/UserUtils.java
src/test/java/site/goldenticket/domain/user/controller/UserControllerTest.java
src/test/java/site/goldenticket/domain/user/wish/controller/WishProductControllerTest.java

closed #42 
- 계좌 등록 구현 및 통합 테스트
- 계좌 조회 구현 및 통합 테스트

Feature/42 계좌 등록 및 조회 구현

---

src/main/java/site/goldenticket/domain/payment/model/Order.java

not null로 설정해놔서 생기는 문제 일단 기본값으로 false넣어서 해결

fix: customerViewCheck 기본값 false로

---

src/main/java/site/goldenticket/domain/payment/model/Order.java
src/main/java/site/goldenticket/domain/payment/model/Payment.java
src/main/java/site/goldenticket/domain/payment/model/PaymentCancelDetail.java

테이블 컬럼중 id에 대해 명시햇던 이름들 다 삭제,
해당 이슈로 SQLSyntaxErrorException: Unknown column 'o1_0.order_id' in 'field list' 와 같은 오류 해결

Feature/12 테이블 컬럼명 명시 삭제

---

src/main/java/site/goldenticket/common/response/ErrorCode.java
src/main/java/site/goldenticket/domain/user/controller/UserController.java
src/main/java/site/goldenticket/domain/user/dto/ChangePasswordRequest.java
src/main/java/site/goldenticket/domain/user/entity/User.java
src/main/java/site/goldenticket/domain/user/service/UserService.java
src/test/java/site/goldenticket/common/utils/UserUtils.java
src/test/java/site/goldenticket/domain/user/controller/UserControllerTest.java

closed #165 
- 비밀번호 변경 및 테스트
- 기존 비밀번호 확인 후 변경

Feature/165 비밀번호 변경 구현

---

src/main/java/site/goldenticket/domain/chat/dto/response/ChatRoomInfoResponse.java
src/main/java/site/goldenticket/domain/chat/repository/ChatRepository.java
src/main/java/site/goldenticket/domain/chat/service/ChatService.java

- 채팅 정렬 수정: 최신순 -> 등록순
- 시스템 메세지 필터없이 전달
- 구매자, 판매자 ID 추가전달

feat: 채팅방 상세 조회 응답값 수정

---

src/main/java/site/goldenticket/domain/payment/service/PaymentService.java

Feature/12 결제이외의 관련 상태값들 변경

---

src/main/java/site/goldenticket/domain/product/wish/controller/WishProductController.java
src/main/java/site/goldenticket/domain/product/wish/repository/WishProductRepository.java
src/main/java/site/goldenticket/domain/product/wish/service/WishProductService.java
src/test/java/site/goldenticket/domain/product/wish/controller/WishProductControllerTest.java

closed #175 
- 기존 관심 상품 ID로 삭제 -> 사용자 ID와 상품 ID를 통해 삭제하도록 수정

Hotfix/175 관심 상품 삭제 파라미터 수정

---

src/main/java/site/goldenticket/common/response/ErrorCode.java
src/main/java/site/goldenticket/domain/chat/service/ChatService.java

개발내용
-
- 네고 제시, 결제대기중 상태 추가
[채팅방 등록]
- 이미 존재하는 채팅방인 경우
- 상품의 판매자와 구매자의 ID가 동일한 경우
[채팅 등록]
- 존재하지 않는 채팅방,
회원인 경우
- 송신자 타입과 회원 ID가 맞지 않는 경우
- 판매자 또는 구매자가 아닌 회원 ID인 경우

Feature/169 채팅상태 추가(채팅방 상세 조회 API) 및 예외처리 (채팅, 채팅방 생성 API)

---

src/main/java/site/goldenticket/domain/payment/dto/response/PaymentDetailResponse.java
src/main/java/site/goldenticket/domain/payment/dto/response/PaymentReadyResponse.java
src/main/java/site/goldenticket/domain/payment/model/Order.java
src/main/java/site/goldenticket/domain/payment/service/PaymentService.java

- 결제 상세페이지에서 절약금액 보내주기
- 구매자 수수료 3.5로 적용

Feature/12 결제 수정

---

src/main/java/site/goldenticket/domain/user/controller/UserController.java
src/main/java/site/goldenticket/domain/user/dto/ChangeProfileRequest.java
src/main/java/site/goldenticket/domain/user/entity/User.java
src/main/java/site/goldenticket/domain/user/service/UserService.java
src/main/resources/script/schema.sql
src/test/java/site/goldenticket/domain/user/controller/UserControllerTest.java

closed #132 
- 닉네임만 변경 가능
- 변경 전 변경 닉네임 중복 확인

Feature/132 프로필 수정

---

src/main/java/site/goldenticket/domain/nego/dto/response/NegoAvailableResponse.java
src/main/java/site/goldenticket/domain/nego/service/NegoServiceImpl.java
src/main/java/site/goldenticket/domain/payment/service/PaymentService.java

결제 완료 시, 채팅방 없으면 새로 생성
(바로 결제하는 경우에는 네고를 거치지않기 때문에 채팅방이 없음 -> 결제 성공적으로 완료되면 채팅방 생성함)

Feature/183 chat room post  결제 완료 시, 채팅방 없으면 새로 생성

---

src/main/java/site/goldenticket/domain/payment/dto/response/PaymentResponse.java
src/main/java/site/goldenticket/domain/payment/service/PaymentService.java

- 결제 완료 응답값 수정 : 새 채팅방 생성 여부, 채팅방 ID 추가 전달
- 시간초과 혹은 결제 실패 시: false, -1L 반환

feat: 결제 완료 시, 새 채팅방 생성여부 및 채팅방 ID 함께 반환

---

src/main/java/site/goldenticket/domain/chat/service/ChatService.java
src/main/java/site/goldenticket/domain/nego/dto/response/NegoAvailableResponse.java
src/main/java/site/goldenticket/domain/nego/service/NegoServiceImpl.java
src/main/java/site/goldenticket/domain/payment/dto/response/PaymentResponse.java
src/main/java/site/goldenticket/domain/payment/service/PaymentService.java

- 네고 가능여부 조회 api -> 채팅방 생성 -> 입장 + 협의가능 채팅 저장
- 결제완료 -> 채팅방 생성 -> 입장 + 협의가능 채팅 저장
- 새 채팅방 생성 여부 미전달

feat: 채팅방 생성 시 필요한 채팅 저장

---

src/main/java/site/goldenticket/domain/nego/service/NegoServiceImpl.java

기존: 네고 가능할 때에만 채팅방 ID전달
변경: 네고 불가일 때에도 채팅방 ID전달 (네고불가여도 채팅방 조회로 이동하기 때문)

fix: 네고가능여부조회- 모든 경우 채팅방 ID 전달

---

src/main/java/site/goldenticket/domain/chat/service/ChatService.java
src/main/java/site/goldenticket/domain/payment/repository/OrderRepository.java

주문정보 가져오기 전에 있는지 확인해서 주문 없는 에러 나지 않도록 수정

fix: 채팅방 상세 조회시, 채팅 상세 로직 수정

---

src/test/java/site/goldenticket/common/SecurityTest.java
src/test/java/site/goldenticket/common/utils/RestAssuredUtils.java
src/test/java/site/goldenticket/common/utils/UserUtils.java
src/test/java/site/goldenticket/domain/user/controller/UserControllerTest.java

- User 요청 DTO 메서드 분리
- RestAssured 공통 메서드 분리

Feature 테스트에서 공통으로 사용하기 위한 utils 생성

---

src/main/java/site/goldenticket/domain/chat/service/ChatService.java
src/main/java/site/goldenticket/domain/nego/service/NegoSchedulerService.java

- 스케줄러로 인해 자동 양도 완료 처리 시, 구매자 및 판매자에게 시스템메세지 전송

feat: 자동 양도완료(양도승인)관련 시스템 메세지 전송

---

src/main/java/site/goldenticket/domain/nego/service/NegoSchedulerService.java
src/main/java/site/goldenticket/domain/nego/service/NegoServiceImpl.java
src/main/java/site/goldenticket/domain/payment/service/PaymentService.java

- 판매자에게 네고 제안 알림
- 구매자에게 네고 승인 및 20분 내 결제 안내 알림
- 판매자 및 구매자에게 타임오버로 네고 종료 알림
- 판매자에게 결제완료로 양도 여부 선택 알림
- 판매자에게 양도 완료 알림

Feature/233 알림 내용 변경

---

src/main/java/site/goldenticket/domain/nego/service/NegoSchedulerService.java
src/main/java/site/goldenticket/domain/nego/service/NegoServiceImpl.java

Feature/12 자동 양도 완료 관련 수정

---

src/main/java/site/goldenticket/domain/chat/dto/response/ChatRoomInfoResponse.java
src/main/java/site/goldenticket/domain/chat/service/ChatService.java
src/main/java/site/goldenticket/domain/nego/service/NegoServiceImpl.java

feat: 채팅방 상세 조회 응답값 추가(네고가능여부)

---

src/main/java/site/goldenticket/domain/chat/service/ChatService.java

- 채팅방 상세 조회 시, 채팅내역 작성시간 한국시간으로 변환하여 전달
- 자동양도완료 처리 시, 판매자에게 정산안내 시스템 메세지 전송

feat: 채팅방 상세 조회- 한국시간으로 변경, 자동 양도 완료 시, 정산안내 시스템 메세지 전송

---

src/main/java/site/goldenticket/common/response/ErrorCode.java
src/main/java/site/goldenticket/domain/user/entity/User.java
src/test/java/site/goldenticket/common/config/ApiTest.java
src/test/java/site/goldenticket/common/utils/UserUtils.java
src/test/java/site/goldenticket/domain/user/controller/UserControllerTest.java
src/test/java/site/goldenticket/domain/user/entity/UserTest.java
src/test/java/site/goldenticket/domain/user/service/UserServiceTest.java

Feature/사용자 단위 테스트

---

build.gradle
src/docs/asciidoc/index.adoc
src/docs/asciidoc/user.adoc
src/test/java/site/goldenticket/common/config/ApiDocumentation.java
src/test/java/site/goldenticket/common/config/ApiTest.java
src/test/java/site/goldenticket/domain/user/controller/UserControllerTest.java

- Spring REST Docs 사용을 위한 추상클래스 생성
- 회원가입 API 명세 생성

Feature/ Spring REST Docs 공통 설정

---

src/docs/asciidoc/product.adoc
src/main/java/site/goldenticket/common/security/SecurityConfiguration.java
src/main/java/site/goldenticket/domain/product/service/ProductService.java
src/main/java/site/goldenticket/dummy/reservation/controller/MockReservationController.java
src/main/resources/application-test.yml
src/main/resources/application.yml
src/test/java/site/goldenticket/domain/product/controller/ProductControllerTest.java

docs: 야놀자 연동 상품 등록 관련 api 명세 작성
